- name: "Getting the IP address of the base system"
  local_action: command python {{playbook_dir}}/roles/packet-create/files/packet_get_ipaddr.py {{ project_id }} {{ packet_token }} {{ base_system }}
  register: base_sys

- name: Verification Result Failure Status
  fail: msg={{ base_sys.stdout }}
  when: base_sys.stdout | match("!^[0-9]*\.[0-9]*\.[0-9]*\.[0-9]*$")

- name: Verification Result Success Status
  debug: var=base_sys.stdout

- name: "Getting the IP address from Packet server"
  local_action: command python {{playbook_dir}}/roles/packet-create/files/packet_get_ipaddr.py {{ project_id }} {{ packet_token }} {{ device_name }}
  register: sdwan_sys

- name: Verification Result Failure Status
  fail: msg={{ sdwan_sys.stdout }}
  when: sdwan_sys.stdout | match("!^[0-9]*\.[0-9]*\.[0-9]*\.[0-9]*$")

- name: Verification Result Success Status
  debug: var=sdwan_sys.stdout

- name: Adding details to summary file
  local_action: shell echo "Get access VSD at https://{{ sdwan_sys.stdout }}:8443" >> /home/dev/.summary_results
