- name: Restarting Network service
  shell: systemctl restart network
  delegate_to: "{{ sdwan_sys.stdout }}"
  when: sdwan_sys.stdout is defined

#- name: "Reboot server"
#  shell: sleep 2 && shutdown -r now "Ansible updates triggered"
#  async: 1
#  poll: 0
#  ignore_errors: true
#  delegate_to: "{{ sdwan_sys.stdout }}"
#  when: sdwan_sys.stdout is defined
#
#- name: "Waiting until 7.5min for server to come back"
#  local_action: wait_for host={{ sdwan_sys.stdout }} port=22 delay=30 timeout=450

- name: Check if there are dummy interfaces
  shell: ip addr | grep dummy | grep -v grep
  ignore_errors: yes
  changed_when: false
  register: dummy_status
  delegate_to: "{{ sdwan_sys.stdout }}"
  when: sdwan_sys.stdout is defined

- name: Report status of Apache
  fail:
    msg: |
      Dummy interface is not running.
      Return code from `grep`:
      {{ dummy_status.stdout}}
  when: dummy_status.stdout_lines == 0

