- name: "Applying: iptables -t nat -A POSTROUTING -o {{ public_if }} -j MASQUERADE"
  command: "{{ item }}"
  with_items:
    - 'iptables -F'
    - 'iptables -t nat -A POSTROUTING -o {{ public_if }} -j MASQUERADE'
    - 'iptables-save'
  ignore_errors: yes
  delegate_to: "{{ sdwan_sys.stdout }}"
  when: 
    - sdwan_sys.stdout is defined

- name: setting up weave peers
  shell: "{{ item }}"
  with_items:
    - 'weave stop'
#    - 'weave reset'
    - 'weave launch {{ base_sys.stdout }} --ipalloc-range 192.168.0.0/24'
    - 'ip a add 192.168.0.2/24 dev weave'  
  delegate_to: "{{ sdwan_sys.stdout }}"
  ignore_errors: yes

  
