- name: "Applying: iptables -t nat -A POSTROUTING -o {{ public_if }} -j MASQUERADE"
  command: "{{ item }}"
  with_items:
    - 'iptables -t nat -A POSTROUTING -o {{ public_if }} -j MASQUERADE'
    - 'iptables-save'
  ignore_errors: yes
  delegate_to: "{{ sdwan_sys.stdout }}"
  when: 
    - sdwan_sys.stdout is defined

- name: setting up weave peers at {{ sdwan_sys.stdout }}
  shell: "{{ item }}"
  with_items:
    - 'weave stop'
    - 'sleep 10'
    - 'weave launch {{ base_sys.stdout }} --ipalloc-range 192.168.0.0/24'
    - 'ip a add 192.168.0.2/24 dev weave'  
  delegate_to: "{{ sdwan_sys.stdout }}"
  ignore_errors: yes

- name: "Applying: iptables ssh access"
  command: "{{ item }}"
  with_items:
    - 'iptables -A INPUT -i weave -p tcp --dport 22 -j ACCEPT'
    - 'iptables-save'
  ignore_errors: yes
  delegate_to: "{{ sdwan_sys.stdout }}"
  when: 
    - sdwan_sys.stdout is defined


- name: setting up weave peers at {{ base_sys.stdout }}
  shell: "{{ item }}"
  with_items:
#    - 'weave stop'
    - 'weave reset'
    - 'sleep 10'
    - 'weave launch {{ sdwan_sys.stdout }} --ipalloc-range 192.168.0.0/24'
    - 'ip a add 192.168.0.1/24 dev weave'  
  delegate_to: "{{ base_sys.stdout }}"
  ignore_errors: yes

- name: Adding details to summary file
  local_action: shell echo "{{ item }}" >> /home/dev/.summary
  with_items:
    - 'All services has been published thru {{ sdwan_sys.stdout }} address'
    - 'i.e. get access to VSD at https://{{ sdwan_sys.stdout }}:8443'
