
- name: "Add VSC1 to local known_hosts list"
  local_action: shell ssh-keyscan -t rsa {{ vsc1_host }} | sed -e 's/#.*$//' | sed -e '/^$/d' > {{playbook_dir}}/../.ssh/known_hosts

- name: "Create TLS profile at VSC1"
  local_action: command python {{playbook_dir}}/roles/util-deploy/files/nuage_tls_profile.py {{ vsc1_fqdn }} {{ vsc1_host }} {{ vsc1_passwd }} {{ vsc1_cert_name }}
  register: output

- name: Verification Result Failure Status
  fail: msg={{ output.stdout }}
  when: output.stdout != "success"

- name: Verification Result Success Status
  debug: var=output.stdout

- name: "Add VSC2 to local known_hosts list"
  local_action: shell ssh-keyscan -t rsa {{ vsc2_host }} | sed -e 's/#.*$//' | sed -e '/^$/d' > {{playbook_dir}}/../.ssh/known_hosts

- name: "Create TLS profile at VSC2"
  local_action: command python {{playbook_dir}}/roles/util-deploy/files/nuage_tls_profile.py {{ vsc2_fqdn }} {{ vsc2_host }} {{ vsc2_passwd }} {{ vsc2_cert_name }}
  register: output

- name: Verification Result Failure Status
  fail: msg={{ output.stdout }}
  when: output.stdout != "success"

- name: Verification Result Success Status
  debug: var=output.stdout

