- name: "Applying: iptables -t nat -A POSTROUTING -o {{ public_if }} -j MASQUERADE"
  command: "{{ item }}"
  with_items:
    - 'iptables -F'
    - 'iptables -t nat -A POSTROUTING -o {{ public_if }} -j MASQUERADE'
    - 'iptables-save'
  ignore_errors: yes
  delegate_to: "{{ hypervisor }}"
  when: 
    - hypervisor is defined

- name: setting up weave peers
  shell: "{{ item }}"
  with_items:
    - 'weave stop'
#    - 'weave reset'
    - 'weave launch {{ base_system }} --ipalloc-range 192.168.0.0/24'
    - 'ip a add 192.168.0.2/24 dev weave'  
  delegate_to: "{{ hypervisor }}"
  ignore_errors: yes

- name: settings up weave peers from base_system
  shell: "{{ item }}"
  with_items:
    - 'weave stop'
#    - 'weave reset'
    - 'sleep 10'
    - 'weave launch {{ hypervisor }} --ipalloc-range 192.168.0.0/24'
  delegate_to: "{{ base_system }}"
  ignore_errors: yes
  
