---
- name: Removing a ssh key nuage-vns-inabox in packet.net
  packet_sshkey:
    label: nuage-vns-inabox
    key: "{{ lookup('file', '/home/dev/.ssh/id_rsa.pub') }}"
    state: absent
    auth_token: "{{ packet_token }}"

- name: Removing a Bare Metal server
  packet_device:
    project_id: "{{ project_id }}"
    hostnames: sdwan
    plan: baremetal_0
    facility: sjc1
    operating_system: centos_7
    state: absent
    auth_token: "{{ packet_token }}"

